var nombre = 'Juan';
var edad = 10;
var altura = 1.92;
var casado = false;
document.write(nombre);
document.write('<br>');
document.write(edad);
document.write('<br>');
document.write(altura);
document.write('<br>');
document.write(casado);
document.write('<br>');